package steps

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// schemasJSON is generated by cmd/stepschema and kept current by `make
// generate`. See that command for why it is committed rather than reflected at
// runtime.
//
//go:embed schemas.json
var schemasJSON []byte

// Schemas returns a JSON Schema for every step's `with:` block, keyed by the
// value used in `steps[].uses`.
//
// The raw message is handed back rather than a parsed type: the only consumer
// is a form that wants the schema as JSON, and decoding it here just to encode
// it again would be work done to lose nothing but fidelity.
func Schemas() (map[string]json.RawMessage, error) {
	var out map[string]json.RawMessage
	if err := json.Unmarshal(schemasJSON, &out); err != nil {
		return nil, fmt.Errorf("decoding the generated step schemas: %w", err)
	}
	return out, nil
}
